wheel_base:
  length: 0.405      # m
  width: 0.2130      # m
  base_to_rear: 0.20 # m

limits:
  steering: { inner: +30.0, outer: +30.0 } # deg
  max_abs_curvature: 3.0                   # 1/m
  velocity: { min: -1.0, max: 1.0 }        # m/s
  acceleration: { min: -5.0, max: +1.0 }   # m/s^2

wheel_radius: 0.055 # m
gear_ratio: 12