- frame_id: "base"
  child_frame_id: "rplidar_s2::lidar_base"
  translation: {x: 0.0, y: 0.0, z: 0.0}
  rotation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}

- frame_id: "base"
  child_frame_id: "lidar_base"
  translation: {x: 0.0, y: 0.0, z: 0.0}
  rotation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
